Improve context based healthchecks
smallrye/smallrye-health pull request #508
Opened 2023-12-14 14:02 UTC by HerrDerb

2024-01-02 13:26 UTC, xstefank requested changes
Looks good, just a few small changes needed.

2024-01-02 13:26 UTC, xstefank commented on testsuite/experimental/src/test/java/io/smallrye/health/deployment/ContextHealthCheckRegistrar.java
> +public class ContextHealthCheckRegistrar {
This class is not used by the test.

2024-01-02 13:27 UTC, xstefank commented
@HerrDerb, if you could also squash the commits, it would be great. Thanks!

2024-01-02 17:41 UTC, HerrDerb commented on implementation/src/main/java/io/smallrye/health/registry/HealthRegistryImpl.java
> +            throw new IllegalStateException(String.format("Check for ID '%s' already registerds", id));
No this change actually has nothing to do with my usecase. I'll revert that.

2024-01-03 09:51 UTC, xstefank approved these changes

2024-01-03 09:51 UTC, merged

2024-01-03 09:52 UTC, xstefank commented
Thanks @HerrDerb